# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-f4Mjr8bdCy_zMXICPBIum6t0E7OQLaZ
"""

import pandas as pd


data = {
    "Mamlakat": ["AQSh", "Hindiston", "Braziliya", "Rossiya", "Fransiya"],
    "Kasallar soni": [70000000, 62000000, 18000000, 37000000, 24000000],
    "Vafot etganlar": [900000, 100000, 200000, 900000, 500000],
    "Sog'ayganlar": [6500000, 45000000, 80000000, 63000000, 80000000]
}


df = pd.DataFrame(data)


def analyze_covid_data(df):
    print("1. COVID-19 bo'yicha jadval ma'lumotlari:")
    print(df, "\n")

    print("2. Umumiy kasallar soni:")
    print(df["Kasallar soni"].sum(), "\n")

    print("3. Umumiy vafot etganlar soni:")
    print(df["Vafot etganlar"].sum(), "\n")

    print("4. Umumiy sog'ayganlar soni:")
    print(df["Sog'ayganlar"].sum(), "\n")

    print("5. O'lim foizi (%):")
    df["O'lim foizi (%)"] = (df["Vafot etganlar"] / df["Kasallar soni"]) * 100
    print(df[["Mamlakat", "O'lim foizi (%)"]], "\n")

    print("6. Eng ko'p vafot etganlar qaysi mamlakatda:")
    max_deaths = df[df["Vafot etganlar"] == df["Vafot etganlar"].max()]
    print(max_deaths[["Mamlakat", "Vafot etganlar"]], "\n")

    print("7. Eng yuqori o'lim foizi qaysi mamlakatda:")
    max_death_rate = df[df["O'lim foizi (%)"] == df["O'lim foizi (%)"].max()]
    print(max_death_rate[["Mamlakat", "O'lim foizi (%)"]], "\n")


analyze_covid_data(df)