# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwVB5OYfazlee7wyfLc1GW39D8qMB-iP
"""

import pandas as pd
baza={
    "F.I.Sh": [ "Aliveva Marhabo" , "Abdug'afforov Adhamjon" , "Rahmonova Kamola" , "Ne'matov Azizhoji" , "Vahobova Muhlisa" , "Kamoldinov Javlonbek" , "Zuhriddinova Sarvinoz" , "Karimov Muhammadamin" , "Xalimova Xonzoda" , "Madaminov Mahmudjon"],
    "Yoshi": ["19" , "18" , "19" , "19" , "19" , "19" , "19" , "20" , "20" , "18" ] ,
    "Jinsi": [ "qiz bola " , "o'g'il bola" , "qiz bola " , "o'g'il bola" , "qiz bola " , "o'g'il bola" , "qiz bola " , "o'g'il bola" , "qiz bola " , "o'g'il bola" ],
    "Maktab raqami": ["36" , "43" , "12" , "6" , "36" , "39" , "53" , "36" , "12" , "36" , ]
    }
df=pd.DataFrame(baza)
print(df)

df.to_excel("baza.xlsx")

filtr=df.loc[(df["Jinsi"]=="o'g'il bola")&(df["Yoshi"]=="19") ]
print(filtr)

filtr=df.loc[(df["Jinsi"]=="qiz bola ")&(df["Yoshi"]=="19") ]
print(filtr)

filtr=df.loc[(df["Jinsi"]=="o'g'il bola")&(df["Maktab raqami"]=="36") ]
print(filtr)